# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "Deploy to firebase"
 lane :deploy do
  begin
   #Step 1 — Build your app, my suggestion is gym
   #Step 2 — Upload to firebase app distribution
   firebase_app_distribution(
    app: “1:420275361426:android:4ac04a63d0dafee4a5f84b”,
    groups: “alpha”,
    release_notes: “Code improvements”,
    apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
    firebase_cli_path: “C:\Users\webar\AppData\Roaming\npm”,
    firebase_cli_token: “1//0g6Zu5k5rHv9gCgYIARAAGBASNwF-L9IrvYeQwjeGE6VybvTfGbZJ5Rn_sAIbd3xPWUrXHdS-q-UZ0wkqVirVhaQiRkoSKhcaiQI”,
   )
  end
 end
end
